CREATE TABLE IF NOT EXISTS SCENARIO (
	ID_MODULE VARCHAR(20),
    ID_USER INT,
    ID_SCENARIO INT,
    SCEN_NAME TEXT,
    SEARCH VARCHAR(100),
    EMPRESA TEXT,
    GRUPO_ANALISE TEXT,
    PERIODICIDADE VARCHAR(50),
    FLAG_MARCA INT,
    SCEN_TYPE CHAR(1),
    LANGUAGE VARCHAR(50),
    LOCATION VARCHAR(1000),
    FLAG_LOCATION INT,
    TYPE_PERIOD CHAR(5),
    MAP_SELECTION CHAR(10)
);

CREATE TABLE IF NOT EXISTS SCENARIO_OCORRENCIA (
	WORD TEXT,
    QTD INT,
    ORIGEM VARCHAR(50),
    ITEMPESQUISA VARCHAR(1000),
    STATUS VARCHAR(100),
    IDPOST VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS SCENARIO_SENTIMENTO (
	ITEM VARCHAR(50),
    POSITIVO INT,
    NEUTRO INT,
    NEGATIVO INT,
    PERIOD TEXT,
    IDPOST VARCHAR(8000)
);

CREATE TABLE IF NOT EXISTS SCENARIO_LOCATION (
	ITEMPESQUISA TEXT,
    STATUS VARCHAR(100),
    LATITUDE VARCHAR(100),
    LONGITUDE VARCHAR(100),
    ORIGEM VARCHAR(50),
    ADDRESS TEXT,
    IDPOST VARCHAR(1000)
)